#DATA PREPROCESSING AND FEATURE ENGINEERING IN MACHINE LEARNING

Objective:
This assignment aims to equip you with practical skills in data preprocessing, feature engineering, and feature selection techniques, which are crucial for building efficient machine learning models. You will work with a provided dataset to apply various techniques such as scaling, encoding, and feature selection methods including isolation forest and PPS score analysis.

Dataset:
Given "Adult" dataset, which predicts whether income exceeds $50K/yr based on census data.

In [21]:
# importhing Packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [9]:
### loading data
df=pd.read_csv('adult_with_headers (1).csv')

In [11]:
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [12]:
df.shape

(32561, 15)

1.	Handle missing values as per the best practices (imputation, removal, etc.).

In [13]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

There is missing data to handle

In [14]:
### checking for duplicates
df.duplicated().sum()

np.int64(24)

In [19]:
### removing duplicates
df.drop_duplicates(inplace=True,ignore_index=True)
df.duplicated().sum()

np.int64(0)

●	Apply scaling techniques to numerical features:
a.	Standard Scaling   b. Min-Max Scaling

In [20]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [26]:
# Identify Numerical Columns
df_numerical = df.select_dtypes(include=['int64', 'float64']).columns
df_numerical

Index(['age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss',
       'hours_per_week'],
      dtype='object')

In [27]:
# a) Standard Scaling
# Standard Scaling transforms data to have mean = 0 and std = 1.
# Creating standard scaler
standard_scaler = StandardScaler()

# Fit and transform
df_standard_scaled = df.copy()
df_standard_scaled[df_numerical] = standard_scaler.fit_transform(df[df_numerical])

print("Standard Scaled Data:")
print(df_standard_scaled.head())

Standard Scaled Data:
        age          workclass    fnlwgt   education  education_num  \
0  0.030390          State-gov -1.063569   Bachelors       1.134777
1  0.836973   Self-emp-not-inc -1.008668   Bachelors       1.134777
2 -0.042936            Private  0.245040     HS-grad      -0.420679
3  1.056950            Private  0.425752        11th      -1.198407
4 -0.776193            Private  1.408066   Bachelors       1.134777

        marital_status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male
1   Married-civ-spouse     Exec-managerial         Husband   White     Male
2             Divorced   Handlers-cleaners   Not-in-family   White     Male
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female

   capital_gain  capital_loss  hours_per_week  native_country  income
0      0.148292     -0.216743       -0.035664   United-States   <=50K
1     -0.145975     -0.216743       -2.222483   United-States   <=50K
2     -0.145975     -0.216743       -0.035664   United-States   <=50K
3     -0.145975     -0.216743       -0.035664   United-States   <=50K
4     -0.145975     -0.216743       -0.035664            Cuba   <=50K

In [29]:
# b) Min-Max Scaling
# Min-Max Scaling transforms data to a range [0, 1].
# Create MinMacScaler
minmax_scaler = MinMaxScaler()

# Fit and transform MinMaxScaler
df_minmax_scaled = df.copy()
df_minmax_scaled[df_numerical] = minmax_scaler.fit_transform(df[df_numerical])

print("\nMin-Max Scaled Data:")
print(df_minmax_scaled.head())

Min-Max Scaled Data:
        age          workclass    fnlwgt   education  education_num  \
0  0.301370          State-gov  0.044302   Bachelors       0.800000
1  0.452055   Self-emp-not-inc  0.048238   Bachelors       0.800000
2  0.287671            Private  0.138113     HS-grad       0.533333
3  0.493151            Private  0.151068        11th       0.400000
4  0.150685            Private  0.221488   Bachelors       0.800000

        marital_status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male
1   Married-civ-spouse     Exec-managerial         Husband   White     Male
2             Divorced   Handlers-cleaners   Not-in-family   White     Male
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female

   capital_gain  capital_loss  hours_per_week  native_country  income
0       0.02174           0.0        0.397959   United-States   <=50K
1       0.00000           0.0        0.122449   United-States   <=50K
2       0.00000           0.0        0.397959   United-States   <=50K
3       0.00000           0.0        0.397959   United-States   <=50K
4       0.00000           0.0        0.397959            Cuba   <=50K

a.	Standard Scaling   b. Min-Max Scaling
●	Discuss the scenarios where each scaling technique is preferred and why

        Use Standard Scaling for Logistic Regression, SVM, PCA.
        Use Min-Max Scaling for Neural Networks, KNN.
        StandardScaler normalizes features to zero mean and unit variance, while MinMaxScaler rescales features into the range [0,1].
Scaling Techniques: When to Use Which?
        1. Standard Scaling (Z-Score Normalization)
           X(Scaled)  =  X-mu/std
           It transforms data to:
             Mean = 0
             Standard deviation = 1
   When data is approximately normally distributed:
        StandardScaler works best if features follow a bell-shaped distribution.
     For algorithms that assume centered data:   
        Algorithms like:
            Logistic Regression
            Linear Regression
            SVM
            PCA
            LDA
            benefit from zero-mean features for faster and better convergence. 
   When outliers exist but are not extreme:
           Standard scaling is less sensitive than Min-Max to moderate outliers.
   When comparing relative distances matters:
           Since it standardizes variance, it keeps meaningful relationships.
           
2. Min-Max Scaling (Normalization):
     X(scaled) = X-X(min)/x(max)-X(min)
     Transforms data into range: [0, 1
     
   when to use:
      When data does not follow Gaussian distribution,
   
      For algorithms based on distance calculations(KNN, Neural networks, K-means, Gradient Descent based models),
   
      When you need bounded inputs(Neural networks expects values between 0 and 1,
   
      When preserving relative magnitude is important( min-max keeps the original shape of the data.)
   
      When features have known min/max limits

   
  Why we use it:
  
       Ensures uniform scale.
       
       Speeds up learning in neural nets.
       
       Prevents dominance of large-scale features. 
      
Final conclusion: 

      Use Standard Scaling when data is normally distributed and used in linear models, and Min-Max Scaling when algorithms depend on distances or            require bounded input values.

#2. Encoding Techniques:

In [32]:
# ●	Apply One-Hot Encoding to categorical variables with less than 5 categories.
## Identify categorical columns
df_category = df.select_dtypes(include=['object', 'category']).columns
    
##Select categorical columns with less than 5 unique values
low_cardinality_cols = [col for col in df_category if df[col].nunique() < 5]
print("Categorical columns with < 5 categories:")
print(low_cardinality_cols)

Categorical columns with < 5 categories:
['sex', 'income']

In [35]:
# Apply One-Hot Encoding
df_encoded = pd.get_dummies(df, columns=low_cardinality_cols, drop_first=True)
print("\nData after One-Hot Encoding:")
print(df_encoded.head())

Data after One-Hot Encoding:
   age          workclass  fnlwgt   education  education_num  \
0   39          State-gov   77516   Bachelors             13
1   50   Self-emp-not-inc   83311   Bachelors             13
2   38            Private  215646     HS-grad              9
3   53            Private  234721        11th              7
4   28            Private  338409   Bachelors             13

        marital_status          occupation    relationship    race  \
0        Never-married        Adm-clerical   Not-in-family   White
1   Married-civ-spouse     Exec-managerial         Husband   White
2             Divorced   Handlers-cleaners   Not-in-family   White
3   Married-civ-spouse   Handlers-cleaners         Husband   Black
4   Married-civ-spouse      Prof-specialty            Wife   Black

   capital_gain  capital_loss  hours_per_week  native_country  sex_ Male  \
0          2174             0              40   United-States       True
1             0             0              13   United-States       True
2             0             0              40   United-States       True
3             0             0              40   United-States       True
4             0             0              40            Cuba      False

   income_ >50K
0         False
1         False
2         False
3         False
4         False

In [36]:
# Use Label Encoding for categorical variables. Data Exploration and Preprocessing:
df.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32537.000000,3.253700e+04,32537.000000,32537.000000,32537.000000,32537.000000
mean,38.585549,1.897808e+05,10.081815,1078.443741,87.368227,40.440329
std,13.637984,1.055565e+05,2.571633,7387.957424,403.101833,12.346889
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.369930e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [38]:
# Apply Label Encoding
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

df_labelencoded = df.copy()

for col in df_category:
    df_labelencoded[col] = label_encoder.fit_transform(df_labelencoded[col])

print("\nEncoded Data:")
print(df_labelencoded.head())

Encoded Data:
   age  workclass  fnlwgt  education  education_num  marital_status  \
0   39          7   77516          9             13               4
1   50          6   83311          9             13               2
2   38          4  215646         11              9               0
3   53          4  234721          1              7               2
4   28          4  338409          9             13               2

   occupation  relationship  race  sex  capital_gain  capital_loss  \
0           1             1     4    1          2174             0
1           4             0     4    1             0             0
2           6             1     4    1             0             0
3           6             0     2    1             0             0
4          10             5     2    0             0             0

   hours_per_week  native_country  income
0              40              39       0
1              13              39       0
2              40              39       0
3              40              39       0
4              40               5       0

In [39]:
# Load the dataset and conduct basic data exploration (summary statistics, missing values, data types).
# it is already in starting of the code.

In [40]:
# les with more than 5 categories.

In [42]:
# already we have categorial data df_category
low_cardinality = [col for col in df_category if df[col].nunique() <= 5]
high_cardinality = [col for col in df_category if df[col].nunique() > 5]

print("Low-cardinality columns (<=5):", low_cardinality)
print("High-cardinality columns (>5):", high_cardinality)

Low-cardinality columns (<=5): ['race', 'sex', 'income']
High-cardinality columns (>5): ['workclass', 'education', 'marital_status', 'occupation', 'relationship', 'native_country']

In [45]:
# Label Encode high-cardinality(>5)
label_encoder_high = LabelEncoder()
for col in high_cardinality:
    df_labelencoded[col] = label_encoder_high.fit_transform(df_labelencoded[col])

print("\nFinal Encoded Dataset with more than 5 categories:")
print(df_labelencoded.head())

Final Encoded Dataset with more than 5 categories:
   age  workclass  fnlwgt  education  education_num  marital_status  \
0   39          7   77516          9             13               4
1   50          6   83311          9             13               2
2   38          4  215646         11              9               0
3   53          4  234721          1              7               2
4   28          4  338409          9             13               2

   occupation  relationship  race  sex  capital_gain  capital_loss  \
0           1             1     4    1          2174             0
1           4             0     4    1             0             0
2           6             1     4    1             0             0
3           6             0     2    1             0             0
4          10             5     2    0             0             0

   hours_per_week  native_country  income
0              40              39       0
1              13              39       0
2              40              39       0
3              40              39       0
4              40               5       0

In [47]:
#	Discuss the pros and cons of One-Hot Encoding and Label Encoding.
    # forLow-cardinality (≤5) → One-Hot Encoding
    # for High-cardinality (>5) → Label Encoding

 # 3. Feature Engineering:

In [48]:
## suggest new 2 features
   # 1. Workload Level (Hours × Education)
        # Feature: Education_Work_Level
   # 2. Net Capital (capital_gain - capital_loss)
        # Feature: Net_Capital

In [49]:
# 1.Feature: Education_Work_Level
df['Education_Work_Level'] = df['education_num'] * df['hours_per_week']

In [50]:
# 2.Feature: Net_Capital
df['Net_Capital'] = df['capital_gain'] - df['capital_loss']

In [52]:
df.head()  ## our data set along with new features('Education_Work_Level','Net_Capital'

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,Education_Work_Level,Net_Capital
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,520,2174
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,169,0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,360,0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,280,0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,520,0

In [55]:
# ●	Apply a transformation (e.g., log transformation) to at least one skewed numerical feature and justify your choice.
# checking skewness for 'capital gain
capital_gain_skew = df['capital_gain'].skew()
print("Skewness before log transformation for capital_gain is:", capital_gain_skew)

Skewness before log transformation for capital_gain is: 11.949402833551463

In [54]:
# Apply log transformation
df['capital_gain_log'] = np.log1p(df['capital_gain'])

In [56]:
# Check skewness after log transformation
# here we are creating new feature capital_gain_log to not distrubing the original value.
# and checking for the skewness after the log transformation
print("Skewness after log transformation for capital_gain is:", df['capital_gain_log'].skew())

Skewness after log transformation for capital_gain is: 3.094666793136126

In [ ]:
## we observed that the skewness has reduced by applying the log transformation
# it Improves linearity
# Reduces outlier impact
# Stabilizes variance