# Section A: Data Structures & Control Structures

In [1]:
# 1.	Create a list of 5 integers. Perform and print the result of the following operations: 
##      append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [18]:
###### Creating list with 5 integers
list1 = [11,15,20,25,30]
print("Our created list: " , list1)

Our created list:  [11, 15, 20, 25, 30]

In [19]:
### appending numbers to list1
list1.append(60)
list1
print("Our new list with appended value is: ", list1)

Our new list with appended value is:  [11, 15, 20, 25, 30, 60]

In [20]:
# extend
list1.extend([70, 80])
print("Our list after extend:", list1)

Our list after extend: [11, 15, 20, 25, 30, 60, 70, 80]

In [21]:
## insert (inserting 13 at position 2)
list1.insert(2, 13)
print("Our list after insert:", list1)

Our list after insert: [11, 15, 13, 20, 25, 30, 60, 70, 80]

In [22]:
# remove( removing number 40 from our list)
list1.remove(30)
print("our list after remove:", list1)

our list after remove: [11, 15, 13, 20, 25, 60, 70, 80]

In [23]:
# pop
popped_item = list1.pop()
print("our list after pop:", list1)
print("Popped item:", popped_item)

our list after pop: [11, 15, 13, 20, 25, 60, 70]
Popped item: 80

In [24]:
# index
index_value = list1.index(15)
print("Index of 15 is:", index_value)

Index of 15 is: 1

In [25]:
# count( counts the how many times the given number is occured)
count_value = list1.count(20)
print("Count of 20:", count_value)

Count of 20: 1

In [26]:
# sort(gives the list in sorted order, default is ascending order)

list1.sort()
print("our liste after sort: ", list1)

our liste after sort:  [11, 13, 15, 20, 25, 60, 70]

In [27]:
# reverse( it revese the list means the numbers in list will be in reverse order)
list1.reverse()
print("our list after reverse: ", list1)

our list after reverse:  [70, 60, 25, 20, 15, 13, 11]

In [28]:
# clear( list will become empty)
list1.clear()
print("our list after clear: ", list1)

our list after clear:  []

In [ ]:
# 2.Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [1]:
# Creating a tuple with 3 student names
our_tuple = ('pandu','jyo','lassi')
print(our_tuple)

('pandu', 'jyo', 'lassi')

In [2]:
print(type(our_tuple))

<class 'tuple'>

In [3]:
our_tuple[1] = 'buddi'

TypeError: 'tuple' object does not support item assignment

In [4]:
# we can change the value in tuple.Because tuple is ordered and unchangable.
# if we want to change the valuesat a particular position of tuple, we need to copy the tuple into list then we have to change.
tuple1 = ('Radha', 'Krishna','Rukmini')
## below is the example to copy tuple into list and change the value
print(tuple1)

('Radha', 'Krishna', 'Rukmini')

In [5]:
list_tuple = list(tuple1)
print(list_tuple)

['Radha', 'Krishna', 'Rukmini']

In [6]:
list_tuple[2] = 'Gopika'

In [7]:
list_tuple

['Radha', 'Krishna', 'Gopika']

3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [8]:
## creaating set with duplicate integers
set1 = { 1,2,3,3,5,6,7,2,8,9}
print(set1)

{1, 2, 3, 5, 6, 7, 8, 9}

In [9]:
## because, set  does not allow duplicate values.

4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [10]:
## creating a dictionary
dict1 = dict(name = 'jyo', age = 10, city = 'London')
print(dict1)

{'name': 'jyo', 'age': 10, 'city': 'London'}

In [11]:
##3 update the age
dict1.update(age=11)
print(dict1)

{'name': 'jyo', 'age': 11, 'city': 'London'}

In [13]:
#### adding new key 'Email'
dict1["email"] = "Jyomokka@gmail.com"
print(dict1)

{'name': 'jyo', 'age': 11, 'city': 'London', 'email': 'Jyomokka@gmail.com'}

In [14]:
#### final dictionary
dict1

{'name': 'jyo', 'age': 11, 'city': 'London', 'email': 'Jyomokka@gmail.com'}

Write a script that checks if a person is eligible to vote (age ≥ 18). 
Take age as a variable and print the appropriate message.

In [17]:
### declaring variable age
age = int(input("enther the age: "))

enther the age:  12

In [18]:
# checking the eligibility criteria 
if age >= 18:
    print('eligible for vote')
else:
    print('not eligible for vote')

not eligible for vote

6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [30]:
### user input for marks
marks = int(input("enter the marks: "))

enter the marks:  88

In [31]:
### writing code for the conditions given
if marks >= 90:
   print("A")
else:
   if marks in range(75,89):
       print("B")
   else:
      if marks in range(50,74):
         print("C")
      else:   
        if marks <= 50:
           print("fail")

B

In [ ]:
#7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [45]:
# User input
number = int(input("enter the number: "))

enter the number:  -2

In [46]:
## writing the code to chek for the even, positive, negative.
if number > 0:
   if number % 2 == 0:
      print("number is positive even number")
else:
    if number == 0:
        print("number is Zero")
    else:
        print("number is negative")

number is negatice

# Section B: Numpy

In [ ]:
#  8.	Create: - A scalar using np.array(5)
# - A 1D array with values 1 to 5
# - A 2D array (2x3) with values from 10 to 60 in steps of 10

In [2]:
import numpy as np

In [4]:
array1 = np.array(5)
array1

array(5)

In [ ]:
# 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [11]:
my_array = np.random.randint(0,100,size=(4,4))
my_array

array([[18, 73, 97, 52],
       [78, 41, 64, 86],
       [96, 25, 98, 62],
       [59,  1, 98, 77]], dtype=int32)

In [12]:
my_array.shape

(4, 4)

In [ ]:
# 10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [19]:
twod_array = np.random.randint(0,9,size=(3,3))
twod_array

array([[4, 7, 7],
       [5, 4, 3],
       [6, 2, 3]], dtype=int32)

In [20]:
twod_array.shape

(3, 3)

In [ ]:
#Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [21]:
import pandas as pd

In [26]:
df=pd.DataFrame(twod_array,columns=['a','b','c'])

In [27]:
df

   a  b  c
0  4  7  7
1  5  4  3
2  6  2  3

# Section C: Exploring Pandas

In [28]:
#11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
#- Use .info(), .describe()
#- Select 'Name' and 'City' columns
#- Drop 'City' column
#- Fill any missing values in 'Salary' column with the mean
#- Remove any duplicate rows

In [32]:
## creating data manually
data = {"name" : ["Raju","Ravi",'Radha','Mahathi','Jyo','Veera','Keerthi','Naga','Lassi','Buddi'],
        "age" : [32, 40, 35, 11, 9, 40, 38, 39, 10, 8],
        "city" : ['Hyderabad','Khammam','Banglore','London','Windsor','London','Hyderabad','Kodad','Kodad','Banglore'],
        "salary" : [10000,20000,25000,30000,40000,45000,26000,34000,50000,46000]}

In [33]:
## converting data into dataframe
data_frame=pd.DataFrame(data)

In [34]:
data_frame

      name  age       city  salary
0     Raju   32  Hyderabad   10000
1     Ravi   40    Khammam   20000
2    Radha   35   Banglore   25000
3  Mahathi   11     London   30000
4      Jyo    9    Windsor   40000
5    Veera   40     London   45000
6  Keerthi   38  Hyderabad   26000
7     Naga   39      Kodad   34000
8    Lassi   10      Kodad   50000
9    Buddi    8   Banglore   46000